"""
Dump AST to dot file (TODO: generated by LLM, to check)
"""

from graphviz import Digraph
from parser.ast_nodes import *


def pretty_print_ast_after_parsing(ast, filename: str):
    dot = Digraph()

    def add_node(node, parent=None):
        node_id = str(id(node))
        label = type(node).__name__
        dot.node(node_id, label)
        if parent:
            dot.edge(str(id(parent)), node_id)

        for child in node.children:
            add_node(child, node)

    add_node(ast)
    dot.render(filename, format='dot', cleanup=True)


def pretty_print_ast_after_semantic_analysis(ast, filename: str):
    dot = Digraph()

    def add_node(node, parent=None):
        node_id = str(id(node))
        label = f"{type(node).__name__} ({node.semantic_info})"
        dot.node(node_id, label)
        if parent:
            dot.edge(str(id(parent)), node_id)

        for child in node.children:
            add_node(child, node)

    add_node(ast)
    dot.render(filename, format='dot', cleanup=True)
